# vector of images from the registration
sensor_msgs/Image[] registration_images

# vector of transform corresponding to the kinect position for each of the images above
geometry_msgs/Transform[] registration_transforms

# single image frame from the kinect
sensor_msgs/Image kinect_image

# single pointcloud frame from the kinect
sensor_msgs/PointCloud2 kinect_cloud

# the model (pointcloud)
sensor_msgs/PointCloud2 model

---
# transformation the aligns current kinect pointcloud with the model 
geometry_msgs/Transform output_transform